# Site settings
name: Gustavo Narea
keywords: "Software Engineer, Python, Node.js, PostgreSQL, MongoDB, AWS, Docker, Agile, Scrum, Pair Programming"
skills: "Senior Software Engineer in Oxford, UK"
baseurl:

social:
  - title: linkedin
    url: https://www.linkedin.com/in/gustavonarea/
  - title: github
    url: https://github.com/gnarea
  - title: twitter
    url: https://twitter.com/gustavonarea

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1

# Build settings
markdown: kramdown
permalink: pretty
